// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PilamungaSEvaluacion.Data;

#nullable disable

namespace PilamungaSEvaluacion.Migrations
{
    [DbContext(typeof(PilamungaSEvaluacionContext))]
    [Migration("20250428131136_Add-Migration SantiagoPilamunga")]
    partial class AddMigrationSantiagoPilamunga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PilamungaSEvaluacion.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asociado")
                        .HasColumnType("bit");

                    b.Property<float>("DineroSeparar")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumTotalReservas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasDiscriminator().HasValue("Clientes");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PilamungaSEvaluacion.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateOnly>("FechaEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<string>("InformacionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valorpagar")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PilamungaSEvaluacion.Models.PlandeRecompensas", b =>
                {
                    b.HasBaseType("PilamungaSEvaluacion.Models.Clientes");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("PlandeRecompensas");
                });
#pragma warning restore 612, 618
        }
    }
}
